import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Canvas } from '@react-three/fiber';
import { ARButton, XR } from '@react-three/xr';
import { OrbitControls, Environment, ContactShadows } from '@react-three/drei';
import { Info, X } from 'lucide-react';

const ARViewer = () => {
  const { dishId } = useParams();
  const [showInfo, setShowInfo] = useState(false);
  const [dishData, setDishData] = useState(null);

  useEffect(() => {
    // Mock fetching data from Firebase
    setDishData({
      name: 'Truffle Burger',
      price: 18,
      description: 'Juicy wagyu beef patty with truffle mayo, melted cheese, and caramelized onions.',
      nutrition: {
        calories: 850,
        protein: '45g',
        carbs: '40g',
        fat: '55g'
      }
    });

    // Fire Analytics Event (Mock)
    console.log(`[ANALYTICS] Logged AR view for dish: ${dishId} at ${new Date().toISOString()}`);
    // addDoc(collection(db, 'analyticsEvents'), { dishId, timestamp: serverTimestamp(), type: 'view' })

  }, [dishId]);

  if (!dishData) return <div style={{ color: 'white', padding: '2rem', textAlign: 'center' }}>Loading dish data...</div>;

  return (
    <div style={{ width: '100vw', height: '100vh', position: 'relative', overflow: 'hidden' }}>
      
      <ARButton 
        style={{ 
          position: 'absolute', 
          bottom: '2rem', 
          left: '50%', 
          transform: 'translateX(-50%)',
          zIndex: 10,
          padding: '1rem 2rem',
          borderRadius: '30px',
          backgroundColor: 'var(--accent-color)',
          color: 'white',
          border: 'none',
          fontWeight: 'bold',
          cursor: 'pointer',
          boxShadow: '0 4px 14px rgba(0,0,0,0.3)'
        }}
      />

      <div style={{ position: 'absolute', top: 0, left: 0, width: '100%', zIndex: 5, padding: '1.5rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div style={{ background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(10px)', padding: '1rem 1.5rem', borderRadius: '16px' }}>
          <h1 style={{ margin: 0, fontSize: '1.5rem' }}>{dishData.name}</h1>
          <p style={{ margin: 0, color: 'var(--accent-color)', fontWeight: 'bold', fontSize: '1.2rem' }}>${dishData.price}</p>
        </div>
        
        <button 
          onClick={() => setShowInfo(!showInfo)}
          style={{ width: '48px', height: '48px', borderRadius: '50%', padding: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(0,0,0,0.6)', backdropFilter: 'blur(10px)' }}
        >
          {showInfo ? <X /> : <Info />}
        </button>
      </div>

      {showInfo && (
        <div className="animate-fade-in" style={{ 
          position: 'absolute', 
          top: '80px', 
          right: '1.5rem', 
          width: '300px', 
          background: 'rgba(24, 27, 33, 0.9)', 
          backdropFilter: 'blur(10px)', 
          border: '1px solid var(--border-color)',
          padding: '1.5rem', 
          borderRadius: '16px',
          zIndex: 5
        }}>
          <h3 style={{ marginTop: 0 }}>Description</h3>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>{dishData.description}</p>
          
          <h3 style={{ marginTop: '1rem' }}>Nutritional Facts</h3>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', fontSize: '0.9rem' }}>
            <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem', borderRadius: '8px' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Calories</span><br/>
              <b>{dishData.nutrition.calories} kcal</b>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem', borderRadius: '8px' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Protein</span><br/>
              <b>{dishData.nutrition.protein}</b>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem', borderRadius: '8px' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Carbs</span><br/>
              <b>{dishData.nutrition.carbs}</b>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.05)', padding: '0.5rem', borderRadius: '8px' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Fat</span><br/>
              <b>{dishData.nutrition.fat}</b>
            </div>
          </div>
          <p style={{ fontSize: '0.7rem', color: 'var(--accent-color)', marginTop: '1rem', textAlign: 'center' }}>
            ✨ Generated by Gemini AI
          </p>
        </div>
      )}

      <Canvas>
        <XR>
          <ambientLight intensity={0.5} />
          <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} />
          <Environment preset="city" />
          
          {/* Mock 3D Model - A simple burger representation for now */}
          <group position={[0, 0, -1]}>
            <mesh position={[0, 0, 0]}>
              <cylinderGeometry args={[0.3, 0.3, 0.1, 32]} />
              <meshStandardMaterial color="#d4a373" />
            </mesh>
            <mesh position={[0, 0.08, 0]}>
              <cylinderGeometry args={[0.31, 0.31, 0.05, 32]} />
              <meshStandardMaterial color="#4ade80" />
            </mesh>
            <mesh position={[0, 0.15, 0]}>
              <cylinderGeometry args={[0.29, 0.29, 0.1, 32]} />
              <meshStandardMaterial color="#78350f" />
            </mesh>
            <mesh position={[0, 0.25, 0]}>
              <sphereGeometry args={[0.3, 32, 16, 0, Math.PI * 2, 0, Math.PI / 2]} />
              <meshStandardMaterial color="#d4a373" />
            </mesh>
            <ContactShadows position={[0, -0.05, 0]} opacity={0.4} scale={2} blur={2} />
          </group>

          <OrbitControls />
        </XR>
      </Canvas>
    </div>
  );
};

export default ARViewer;
